### ISSUE TITLE
Issue with using CRSs without EPSG code

### ISSUE THREAD

**Issue by ashnair1** [johntruckenbrodt/pyroSAR#126] opened 2021-02-08 20:08 UTC
**OS:**
Ubuntu 18.04

**Environment Used:** 
Anaconda environment

**Library versions:**
pyroSAR: version 0.11.1 from conda-forge
SNAP: 8.0

**Objective:**
I wanted to reproject (to South LAEA) and apply speckle filtering to a couple of Sentinel SAR images that I have acquired. However I am unable to do so.

**Code:**

```
from pathlib import Path
from pyroSAR.snap import geocode

outdir = './outdir'
# South Lambert Equal Area Projection (ESRI:102020)
out_proj = "+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

sar_zips = [ str(Path.cwd() / i) for i in Path('./data').iterdir() if i.suffix == ".zip"]
geocode(infile=sar_zips[0], outdir=outdir, t_srs=out_proj, speckleFilter="Lee")
```

This snippet outputs
```
searching for new POE files
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1B&validity_start__gte=2019-08-19T07:52:49&validity_stop__lte=2019-08-21T07:52:49
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-10d2a2932d21> in <module>
----> 1 geocode(infile=sar_zips, outdir=outdir, t_srs=out_proj, speckleFilter="Lee")

~/anaconda3/envs/sar/lib/python3.6/site-packages/pyroSAR/snap/util.py in geocode(infile, outdir, t_srs, tr, polarizations, shapefile, scaling, geocoding_type, removeS1BorderNoise, removeS1BorderNoiseMethod, removeS1ThermalNoise, offset, allow_RES_OSV, demName, externalDEMFile, externalDEMNoDataValue, externalDEMApplyEGM, terrainFlattening, basename_extensions, test, export_extra, groupsize, cleanup, gpt_exceptions, gpt_args, returnWF, nodataValueAtSea, demResamplingMethod, imgResamplingMethod, speckleFilter, refarea)
    384 
    385     try:
--> 386         t_srs = crsConvert(t_srs, 'epsg')
    387     except TypeError:
    388         raise RuntimeError("format of parameter 't_srs' not recognized")

~/anaconda3/envs/sar/lib/python3.6/site-packages/spatialist/auxil.py in crsConvert(crsIn, crsOut)
     77         return srs.ExportToProj4()
     78     elif crsOut == 'epsg':
---> 79         srs.AutoIdentifyEPSG()
     80         return int(srs.GetAuthorityCode(None))
     81     elif crsOut == 'opengis':

~/anaconda3/envs/sar/lib/python3.6/site-packages/osgeo/osr.py in AutoIdentifyEPSG(self, *args)
    564     def AutoIdentifyEPSG(self, *args):
    565         """AutoIdentifyEPSG(SpatialReference self) -> OGRErr"""
--> 566         return _osr.SpatialReference_AutoIdentifyEPSG(self, *args)
    567 
    568 

RuntimeError: OGR Error: Unsupported SRS
```

Edit: I tried using osr and importing the wkt representation of South LAEA

```
wkt = """PROJCS["South_Pole_Lambert_Azimuthal_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["False_Easting",0],PARAMETER["False_Northing",0],PARAMETER["Central_Meridian",0],PARAMETER["Latitude_Of_Origin",-90],UNIT["Meter",1],AUTHORITY["EPSG","102020"]]"""
out_proj2 = osr.SpatialReference(wkt)

geocode(
    infile=sar_zips[0],
    outdir=outdir,
    t_srs=out_proj2,
    scaling="linear",
    speckleFilter="Refined Lee",
)

```
This worked till the Terrain Correction part, but failed for a similar reason. 

```
searching for new POE files
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1A&validity_start__gte=2020-03-16T22:55:06&validity_stop__lte=2020-03-18T22:55:06
unpacking scene
removing border noise..
border noise removal not necessary for IPF version 3.2
executing node sequences..
ThermalNoiseRemoval
Apply-Orbit-File
Calibration
Terrain-Flattening
Speckle-Filter
Terrain-Correction
Executing processing graph
No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
 done.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Incompatible GDAL 3.1.4 found on system. Internal GDAL 3.0.0 from distribution will be used.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
INFO: org.hsqldb.persist.Logger: dataFileCache open start
org.esa.snap.core.gpf.graph.GraphException: [NodeId: Terrain-Correction] No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:79)
	at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:199)
	at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:182)
	at org.esa.snap.core.gpf.graph.GraphContext.initOutput(GraphContext.java:166)
	at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:85)
	at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:58)
	at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:118)
	at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:86)
	at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:547)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:391)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:287)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
	at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
	at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.esa.snap.runtime.Launcher1159904018.main(Unknown Source)
Caused by: org.esa.snap.core.gpf.OperatorException: No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.esa.snap.engine_utilities.gpf.OperatorUtils.catchOperatorException(OperatorUtils.java:440)
	at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.initialize(RangeDopplerGeocodingOp.java:349)
	at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:528)
	at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:298)
	at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:385)
	at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:77)
	... 29 more
Caused by: org.esa.snap.core.gpf.OperatorException: No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.createTargetProduct(RangeDopplerGeocodingOp.java:564)
	at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.initialize(RangeDopplerGeocodingOp.java:306)
	... 33 more
Caused by: org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".
	at org.geotools.referencing.factory.AbstractAuthorityFactory.noSuchAuthorityCode(AbstractAuthorityFactory.java:875)
	at org.geotools.referencing.factory.epsg.DirectEpsgFactory.createCoordinateReferenceSystem(DirectEpsgFactory.java:2239)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:732)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:780)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:732)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:780)
	at org.geotools.referencing.factory.FallbackAuthorityFactory.createCoordinateReferenceSystem(FallbackAuthorityFactory.java:625)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:780)
	at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:636)
	at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:177)
	at org.geotools.referencing.CRS.decode(CRS.java:517)
	at org.esa.s1tbx.commons.CRSGeoCodingHandler.getCRS(CRSGeoCodingHandler.java:173)
	at org.esa.s1tbx.commons.CRSGeoCodingHandler.<init>(CRSGeoCodingHandler.java:55)
	at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.createTargetProduct(RangeDopplerGeocodingOp.java:530)
	... 34 more

Error: [NodeId: Terrain-Correction] No code "EPSG:102020" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".

[S1A_EW_GRDH_1SSH_20200317T225506_20200317T225606_031721_03A873_CB43_tmp5.xml] failed with return code 1
failed: ./outdir/S1A__EW___A_20200317T225506_HH_NR_Orb_TF_Spk_TC/S1A__EW___A_20200317T225506_HH_NR_Orb_TF_Spk_TC_proc.xml

```

How can I correctly reproject my SAR files to South LAEA using pyroSAR?

**Comment by johntruckenbrodt** [comment] 2021-02-16 09:08
Hi @ashnair1, the central function for CRS handling in pyroSAR is [spatialist.crsConvert](https://spatialist.readthedocs.io/en/latest/spatialist.html#spatialist.auxil.crsConvert), which makes use of OSR. First, the CRS input to the geocode function is converted to EPSG so that the CRS can we written in the SNAP XML workflow like this: 'EPSG:4326' to save space.
The South LAEA CRS apparently does not have a EPSG code. However, in the following example the ESRI code is returned as EPSG code:
```python
from osgeo import osr

crs = """PROJCS["South_Pole_Lambert_Azimuthal_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["False_Easting",0],PARAMETER["False_Northing",0],PARAMETER["Central_Meridian",0],PARAMETER["Latitude_Of_Origin",-90],UNIT["Meter",1],AUTHORITY["EPSG","102020"]]"""

srs = osr.SpatialReference(crs)

# convert to EPSG code
srs.AutoIdentifyEPSG()
auth = srs.GetAuthorityName(None)
code = int(srs.GetAuthorityCode(None))
string = '{}:{}'.format(auth, code)
print(string)

# re-convert EPSG code to OSR SpatialReference
# will fail because EPSG code 102020 is not recognized
srs = osr.SpatialReference()
srs.ImportFromEPSG(code)
print(srs)
```
I don't know why this happens. I am sure there is a reason for it but to me it looks strange.  
I have introduced a new check in `crsCovert` with commit johntruckenbrodt/spatialist@5e803b4 so that 102020 is not returned as EPSG code (because it is an ESRI code) but a `RuntimeError` is raised instead.
In a next step I'll adjust the `geocode` function so that the WKT representation is written to the SNAP workflow if this error occurs.
I'll keep you posted on my progress.

**Comment by johntruckenbrodt** [comment] 2021-02-18 11:22
Okay I've played around with it a little bit. I directly wrote the WKT in the XML workflow but this did not work either. If you select the CRS in the graph builder you will not find the CRS as an option, because only ones with an EPSG code are listed. There is an option to define a custom CRS though. You could try defining it there, saving the graph as XML, and copying the WKT representation from the XML file into Python.

**Comment by ashnair1** [comment] 2021-02-18 11:40
Ok, I'll try that method.

**Comment by ashnair1** [comment] 2021-02-20 11:41
I was able to successfully preprocess it in SNAP by using the following wkt

```
PROJCS["Lambert_Azimuthal_Equal_Area / European Terrestrial Reference System 1989", 
  GEOGCS["European Terrestrial Reference System 1989", 
    DATUM["European Terrestrial Reference System 1989", 
      SPHEROID["GRS 1980", 6378137.0, 298.257222101, AUTHORITY["EPSG","7019"]], 
      TOWGS84[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 
      AUTHORITY["EPSG","6258"]], 
    PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
    UNIT["degree", 0.017453292519943295], 
    AXIS["Geodetic longitude", EAST], 
    AXIS["Geodetic latitude", NORTH]], 
  PROJECTION["Lambert_Azimuthal_Equal_Area"], 
  PARAMETER["latitude_of_center", 0.0], 
  PARAMETER["longitude_of_center", 0.0], 
  PARAMETER["false_easting", 0.0], 
  PARAMETER["false_northing", 0.0], 
  UNIT["m", 1.0], 
  AXIS["Easting", EAST], 
  AXIS["Northing", NORTH]]

```

However, this CRS still isn't accepted by pyroSAR as it keeps giving me `RuntimeError: OGR Error: Unsupported SRS`. I've added my workflow in my other issue [here](#127)

**Comment by johntruckenbrodt** [comment] 2021-03-02 17:55
I believe the reason is that this function [spatialist.crsConvert](https://spatialist.readthedocs.io/en/latest/spatialist.html#spatialist.auxil.crsConvert) reads the WKT into an `osr.SpatialReference` object and then exports it to WKT again. This is of course not that elegant and I suspect that in this procedure the WKT is modified so that it does no longer work with SNAP.  
@ashnair1, I guess your problem with this is now fixed with the solution in issue #127, but I'll leave it open so that this can be fixed for the `geocode` function as well.

**Comment by davedavemckay** [comment] 2021-06-21 20:31
Hi @johntruckenbrodt 
Unfortunately, after installing the latest master of spatialist the error "'t_srs' not recognized in geocode call" is still reported.
As I said in #147, I was using epsg=27700 or an equivalent PROJ4 string.
Thanks

**Comment by davedavemckay** [comment] 2021-06-24 09:02
Hi,
Not sure how relevant this is, but I have working and non-working systems where I run (identical) scripts using `t_srs = crs_epsg = 27700`. I have attached a `pip freeze` for each of these systems in case you spot something I didn't.
[working_pip.txt](https://github.com/johntruckenbrodt/pyroSAR/files/6707828/working_pip.txt)
[not_working_pip.txt](https://github.com/johntruckenbrodt/pyroSAR/files/6707829/not_working_pip.txt)
I note two potentially significant differences:
spatialist version 0.5 in the working environment vs 0.6 (then 0.7.dev8+g302851e) in the non-working env;
PROJ version 6.3.2 (working) vs 6.0.0 (non-working).
Further to the Python environments, the setups include:
```
Python 3.9.2 # running a virtualenv under a pyenv installation
GDAL 3.0.0, released 2019/05/05 # both systems
PROJ Rel. 6.3.2, May 1st, 2020 # working
PROJ Rel. 6.0.0, March 1st, 2019 # non-working
SNAP 8.0 # both systems
s1tbx 8.0.4 # both systems
```

While writing this I installed `spatialist==0.5` on the non-working system and I still see `format of parameter 't_srs' not recognized` there. Also just tested - the working system works!!
Any help much appreciated,
Dave

**Comment by davedavemckay** [comment] 2021-06-30 16:34
Hi John, thanks for the updates.
You're right, that doesn't work, but the error is not `format of parameter 't_srs' not recognized` but `RuntimeError: PROJ: proj_create_from_database: Cannot find proj.db`
From https://stackoverflow.com/a/57853508/4841654 and the comment below it I changed PROJ_LIB from "~/proj" to "~/proj/share/proj" (the latter contains proj.db) and my code now works!
After 2 weeks of comparing Python environments, the problem is a path! I should get "the problem is a path" on a t-shirt!!
Thanks for all your help!

**Comment by johntruckenbrodt** [comment] 2021-07-01 06:52
For sure, path issues always add some spice to our daily work :stuck_out_tongue_winking_eye:. Glad you found the error and sorry for not being able to respond sooner.

The conda package of `spatlialist` version 0.7 is now online. Looks like this is under control.

**Closed by johntruckenbrodt** 2021-07-01 06:52 UTC
Labels: bug
