### ISSUE TITLE
>100m spatial offset in processed GRD data

### ISSUE THREAD

**Issue by DTMilodowski** [johntruckenbrodt/pyroSAR#178] opened 2021-12-15 14:45 UTC
- which operating system are you using?  
Ubuntu 20.04.3
- which environment is pyroSAR running in?  anaconda environment
- which version of pyroSAR are you using?  0.14
-  which function of pyroSAR did you call with which parameters?  geocode, with external DEM

This might be a quick one, and maybe just needs a sentence added to documentation, but I noticed a ~100-150m offset in GRD data processed with the geocode function, with the range-doppler terrain correction. I'm using an external DEM, which links to a copy of the copernicus GLO30 DEM.

In my initial attempt, I had externalDEMApplyEGM=True (the default). I ended up with a similar offset using the default SRTM DEM, rather than an external DEM. After some exploration of different DEMs and keyword argument combinations, I resolved the offset issue by setting externalDEMApplyEGM=False in the geocode function. Is this expected behaviour for this function or have I missed something (quite likely!)?

Thanks again for a super-useful package!

Best wishes,
David

**Comment by johntruckenbrodt** [comment] 2021-12-15 15:06
Hi David. These 100-150 m are very likely related to some geoid conversion problem. The vertical datum of the Copernicus DEM is EGM2008, but SNAP only supports EGM96 with `externalDEMApplyEGM=True`. It is surprising however that you get the same offset with SRTM.
I suggest trying to do the EGM correction yourself using [pyroSAR.auxdata.dem_create](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.auxdata.dem_create) with `geoid='EGM2008'`. See the [DEM preparation](https://pyrosar.readthedocs.io/en/latest/general/DEM.html#) documentation section for details.

Cheers,
John

**Comment by DTMilodowski** [comment] 2021-12-15 15:09
Awesome, thanks for the rapid response! I'll play around with your suggested EGM correction this afternoon :-)

**Comment by DTMilodowski** [comment] 2021-12-17 16:21
Update!

I've tried various iterations, and DEMs, and I'll summarise the results below. Short version I end up with an offset using the SRTM DEM, and when I apply the EGM2008 to the glo30 DEM. I get a nicely aligned image if I use glo30 and _do not apply EGM2008_. I'd be interested to know whether I've missed something, or if the latter is the best option.

The scene in question is this: S1B_IW_GRDH_1SDV_20211107T062922_20211107T062947_029478_03848E_6E05.zip

I've subset it in the analysis to speed things along.

--------------
DEM #1 SRTM, with the command below, gives an **offset result** (image shows comparison against open street map layer):
```
geocode('%s.zip' % scene['Granule Name'], outdir=outdir,shapefile=bbox_shp,
    t_srs=27700, tr=resolution, scaling='dB', polarizations='all',  geocoding_type='Range-Doppler',
    removeS1BorderNoise=True,  removeS1BorderNoiseMethod='pyroSAR', removeS1ThermalNoise=True, terrainFlattening=True, demName='SRTM 1Sec HGT', speckleFilter=False, refarea='gamma0',alignToStandardGrid = True, standardGridOriginX = origin[0], standardGridOriginY = origin[1], allow_RES_OSV=False)
```
![image](https://user-images.githubusercontent.com/3473480/146570623-51d601b8-7401-4686-9277-5431c7ba4dad.png)

--------------
DEM #2 Copernicus glo30 DEM, applying the dem_create() function to convert to geoid heights, but setting externalDEMApplyEGM=False gives an **offset result** similar to the above:

```
dem_create(src=dem_in,dst=dem_out,resampling_method='bilinear',geoid_convert=True,geoid='EGM2008')

geocode('%s.zip' % scene['Granule Name'],  outdir=outdir, shapefile=bbox_shp, t_srs=27700, tr=resolution, scaling='dB', polarizations='all', geocoding_type='Range-Doppler', removeS1BorderNoise=True, removeS1BorderNoiseMethod='pyroSAR', removeS1ThermalNoise=True, terrainFlattening=True, 
 externalDEMFile=dem_file_egm2008, externalDEMNoDataValue=dem_ndv, externalDEMApplyEGM=False, speckleFilter=False, refarea='gamma0', alignToStandardGrid = True, standardGridOriginX = origin[0], standardGridOriginY = origin[1], allow_RES_OSV=False)
```

![image](https://user-images.githubusercontent.com/3473480/146572915-3db05d53-cf61-4cb8-9695-9c73bdae0e98.png)

Setting externalDEMApplyEGM=True with an otherwise identical setup yields **a larger offset**, further offset in the same direction

![image](https://user-images.githubusercontent.com/3473480/146573519-729829b1-c1ab-4fa1-a176-e165d387a5ec.png)


--------------
DEM #3:  Copernicus glo30 DEM, the original version downloaded from ESA, and setting externalDEMApplyEGM=False gives a **near-perfectly aligned result**. :

```
geocode('%s.zip' % scene['Granule Name'], outdir=outdir,shapefile=bbox_shp,
    t_srs=27700, tr=resolution, scaling='dB', polarizations='all', geocoding_type='Range-Doppler',
    removeS1BorderNoise=True, removeS1BorderNoiseMethod='pyroSAR',removeS1ThermalNoise=True, terrainFlattening=True,
    externalDEMFile=dem_file_no_egm, externalDEMNoDataValue=dem_ndv, externalDEMApplyEGM=False, speckleFilter=False,
    refarea='gamma0',alignToStandardGrid = True, standardGridOriginX = origin[0], standardGridOriginY = origin[1],allow_RES_OSV=False)

```

![image](https://user-images.githubusercontent.com/3473480/146574406-4ee07e3d-0d32-4c96-8f06-aaedbe38edf6.png)

**_I am tempted to say that this would be the optimal solution, but I it doesn't apply the EGM_.**

Setting externalDEMApplyEGM=True in the above geocode call leads to an **offset result**, similar to the SRTM example:
![image](https://user-images.githubusercontent.com/3473480/146574607-460e3a50-a047-4df6-8381-1d05ab17095a.png)

--------------
Thank you so much for your feedback!

**Comment by maawoo** [comment] 2021-12-20 08:58
Hi David!
You have not mentioned which SNAP and S1TBX versions are installed. Have you opened the SNAP GUI recently to check if updates are available?
Also [this](https://forum.step.esa.int/t/sentinel-1-preprocessing-problem-with-terrain-correction/5427/6) is probably related. Maybe try using `t_srs=4326` first (also for your DEM) and reproject to the CRS you want afterwards using GDAL.

**Comment by DTMilodowski** [comment] 2021-12-22 15:52
Hi Marco,

Thank you for your response. I am using SNAP version 8 and it's up to date.

The link to the forum post was very helpful. I'd not found it previously. Running the analysis with the target CRS as either 4326 or the local UTM zone (32630), with the egm-adjusted DEM seems to work well, i.e.:

```
geocode('%s.zip' % scene['Granule Name'], outdir=outdir,shapefile=bbox_shp,
    t_srs=32630, tr=resolution, scaling='dB', polarizations='all', geocoding_type='Range-Doppler',
    removeS1BorderNoise=True, removeS1BorderNoiseMethod='pyroSAR',removeS1ThermalNoise=True, terrainFlattening=True,
    externalDEMFile=dem_file_egm2008, externalDEMNoDataValue=dem_ndv,externalDEMApplyEGM=True, speckleFilter=False,
    refarea='gamma0',allow_RES_OSV=False)
```

So, it would appear that there is a SNAP-related issue specifically relating to the definition of the OSGB coordinate system (EPSG:27700) which leads to the spatial errors when applying the terrain correction.

Thanks again @johntruckenbrodt and @maawoo, and Merry Christmas!

**Comment by maawoo** [comment] 2021-12-23 12:00
Hi David, 
happy that this was helpful! 
I've posted in the forum thread and pointed to this issue. Maybe this will be resolved in an upcoming SNAP update.

Merry Christmas 🎄

**Comment by johntruckenbrodt** [comment] 2022-01-05 14:25
Hi @DTMilodowski and @maawoo. Happy new year! Great you were able to identify the cause. Let's hope this is fixed soon.

**Comment by johntruckenbrodt** [comment] 2022-01-05 14:27
I am closing this for now as it is not a pyroSAR bug. Please feel free to reopen it if needed.

**Closed** 2022-01-05 14:27 UTC
Labels: bug
