### ISSUE TITLE
SNAP [NodeId: Read] The 'file' parameter is not set

### ISSUE THREAD

**Issue by marielaraj** [johntruckenbrodt/pyroSAR#97] opened 2019-11-19 09:12 UTC
Hello, 

I have been trying to use geocode with the following file:
scene = S1B_IW_GRDH_1SDV_20180317T091416_20180317T091441_010069_01244C_EB9B.zip'

geocode(infile=scene, outdir=outdir,t_srs=32721, shapefile=testsite, scaling="linear", removeS1ThermalNoise=False, externalDEMFile=externaldem, externalDEMApplyEGM=False)

And I got this error:
searching for new POE files
(..)
Subset
Executing processing graph
 done.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/home/software/GDAL-2.4.2/lib::/home/software/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib'.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.

Error: [NodeId: Read] The 'file' parameter is not set

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/util.py", line 526, in geocode
    removeS1BorderNoiseMethod=removeS1BorderNoiseMethod)
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 257, in gpt
    execute(sub, cleanup=cleanup, gpt_exceptions=gpt_exceptions)
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 163, in execute
    print('failed: {}'.format(os.path.basename(infile)))
  File "/usr/lib64/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Thank you very much.
Mariela.

**Comment by johntruckenbrodt** [comment] 2019-11-19 12:18
Hi @marielaraj,

thanks for reporting this bug. I am on it.

Cheers,
John

**Comment by johntruckenbrodt** [comment] 2019-11-19 16:47
Hi @marielaraj and @jeosnes,
I processed the scene but so far was not able to reproduce your problem.  
The following worked for me:  
```python
import os
from pyroSAR import identify
from pyroSAR.snap import geocode
from spatialist import Vector
from pyroSAR.auxdata import dem_autoload, dem_create

maindir = '/somepath'

scene = 'S1B_IW_GRDH_1SDV_20180317T091416_20180317T091441_010069_01244C_EB9B.zip'
scene = os.path.join(maindir, scene)

# just a dummy shapefile with the full scene extent to test whether passing a 
# geometry in function geocode works
bbox = os.path.join(maindir, 'bbox.shp')
if not os.path.isfile(bbox):
    id = identify(scene)
    id.bbox(bbox)

# create a DEM with the shapefile extent in UTM and WGS84 ellipsoid heights
externaldem = os.path.join(maindir, 'dem.tif')
if not os.path.isfile(externaldem):
    vrt = os.path.join(maindir, 'dem.vrt')
    with Vector(bbox) as site:
        vrt = dem_autoload([site], 'SRTM 1Sec HGT', vrt=vrt)
        dem_create(src=vrt, dst=externaldem,
                   t_srs=32721, tr=(20, 20),
                   resampling_method='bilinear',
                   geoid_convert=True, geoid='EGM96')
    os.remove(vrt)

outdir = os.path.join(maindir, 'proc')

with Vector(bbox) as site:
    wf = geocode(infile=scene, outdir=outdir, t_srs=32721, shapefile=site,
                 removeS1ThermalNoise=False, scaling='db', tr=100,
                 externalDEMFile=externaldem, externalDEMApplyEGM=False,
                 returnWF=True, test=False)
```
So far I have only tried this with the current master branch on GitHub and not the latest PyPI version.
Can you try whether this works for you? What version of pyroSAR are you using?

Cheers,
John

**Comment by marielaraj** [comment] 2019-11-20 09:09
Hi @johntruckenbrodt ,

thank you for your prompt answer.
I am using the latest PyPI version: '0.9.2.dev103+g57eeb30'.

I tried again with your code and had the same problem:
WARNING: org.esa.snap.core.util.VersionChecker: Not able to check for new SNAP version. Remote version could not be retrieved.

Error: [NodeId: Read] The 'file' parameter is not set

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/util.py", line 526, in geocode
    removeS1BorderNoiseMethod=removeS1BorderNoiseMethod)
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 257, in gpt
    execute(sub, cleanup=cleanup, gpt_exceptions=gpt_exceptions)
  File "/home/le67hed/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 163, in execute
    print('failed: {}'.format(os.path.basename(infile)))
  File "/usr/lib64/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Best, 
Mariela.

**Comment by johntruckenbrodt** [comment] 2019-11-20 09:30
Hi Mariela,

a PyPI version would only have a name like `0.9.2`. Your version is a clone from GitHub displayed as `{next_version}.dev{distance}+{scm letter}{revision hash}` (see [here](https://www.diycode.cc/projects/pypa/setuptools_scm)).  
You are currently using a version from October 18 when the commit 57eeb30 was made.  
Can you please update your installation/clone and try again?

Cheers,
John

**Comment by johntruckenbrodt** [comment] 2019-11-20 13:11
Closing this for now since the bug was fixed with updating the software to the latest commit on GitHub.

**Closed by johntruckenbrodt** 2019-11-20 13:11 UTC
Labels: bug
