### ISSUE TITLE
Concurrent processing in ECS cluster causes all processes to hang

### ISSUE THREAD

**Issue by matthewhanson** [johntruckenbrodt/pyroSAR#104] opened 2020-01-14 19:37 UTC
- which operating system are you using?  
Amazon Linux 2, also locally with Ubuntu 18.04

- which environment is pyroSAR running in?  
Docker image running in ECS cluster, also locally

- which version of pyroSAR are you using?  
0.10.1

-  which function of pyroSAR did you call with which parameters?  
```
from pyroSAR.S1 import OSV
osvdir = '/root/.snap/auxdata'
with OSV(osvdir) as osv:
    files = osv.catch(sensor='S1A', osvtype='POE',
                      start='20190501T000000', stop='20200114T000000')
    print(files)
    osv.retrieve(files)
```

- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
SNAP 7

- the full error message
just hangs, doesn't download any part of the files

#####

I'm getting a problem downloading the Orbit files. At first this was just causing hanging within my AWS Batch task, but it wasn't clear where the problem lies due logging not being propagated from PyroSAR to CloudWatch for some reason (my library logs properly, but everything from PyroSAR is absent).

So I tried to instead fetch a batch of them locally, and it gets the filenames, but when I call retrieve it doesn't even start downloading them and just hangs indefinitely.  This should at least timeout, it was extremely difficult to narrow this down.

```
>>> osv.retrieve(files)
downloading 238 files
  0% (1 of 238) |                                                                     | Elapsed Time: 0:08:22 ETA:  1 day, 9:04:18
```

**Comment by matthewhanson** [comment] 2020-01-14 19:47
I should add that download the files manually from https://qc.sentinel1.eo.esa.int/ works

**Comment by matthewhanson** [comment] 2020-01-14 21:33
Looks like this was not entirely the case - it's just that the progress bar is broken and not showing any progress, but it was downloading files, when running locally.

I'm still trying to figure out why it's hanging when running in a cluster.

**Comment by matthewhanson** [comment] 2020-01-15 13:04
I've narrowed down this problem sort of, although I'm still not understanding the cause.

When I run this locally, it all works fine.  But when I run on an EC2 instance (the file has been download locally), there's stdout gets buffered at some point between the start of the geocode function and the end of the geocode function, and it only flushes to the stdout logs at the end of the function.   And so when it hangs, it happens somewhere in this function, but I can't tell where exactly.

**Comment by matthewhanson** [comment] 2020-01-16 17:19
After some more testing I'm still not sure where this problem lies, so not sure if you want to keep this bug report open or not.

What's clear is that as soon as I try to process more than 10 files at one time on a cluster, they all stop logging and hang at the same spot, which looks to be right at the "ThermalNoiseRemoval -> Apply-Orbit-File -> Calibration" step.

It's really quite strange, because there's no plausible reason why separate tasks on separate instances in a cluster would either all hang or none at all, so it suggests some external influence here.

For now I'm keeping cores and mem high to process each one as quick as possible but keeping the concurrent limit to 10, which is working.  But at some point in the future I'm going to need to scale this up even more and will have to revisit this.

**Comment by johntruckenbrodt** [comment] 2020-01-16 17:32
Hi @matthewhanson,
thanks for the comprehensive report and sorry to hear you had a hard time figuring out the cause of your error. 
Referring to your issue #105, I have made the progress bar optional and disabled it per default so that should get out of your way now.
I also had the feeling there are some things wrong with the progress bar's stdout buffering. For example, when I print a message, add the pbar, and directly after print another message, the order is often mixed up so that first the two messages appear and then the pbar. In particular if the pbar only has a very short length.  
Could you check whether the stdout problem in geocode is already fixed with this?  
From your experience, what do you suggest for timeout? Check only one file and if the timeout is exceeded terminate the whole thing or try downloading another file? So far I never really though about this and should implement this for several tools in pyroSAR.

Regards,
John

**Comment by johntruckenbrodt** [comment] 2022-02-07 14:46
Closing this for now as it has been inactive for a long time. Feel free to reopen if necessary.

**Closed by johntruckenbrodt** 2022-02-07 14:46 UTC
Labels: bug
